In [2]:
# NumPy arrays

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,4,4)

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5,5)

array([[0.61684485, 0.73462297, 0.00973052, 0.43026691, 0.14774622],
       [0.12014028, 0.93869845, 0.80012293, 0.86762291, 0.24685766],
       [0.59099729, 0.48919173, 0.21463185, 0.55753503, 0.86923143],
       [0.34253069, 0.86123906, 0.81812623, 0.57650244, 0.62746811],
       [0.30018769, 0.04353437, 0.65095093, 0.21042386, 0.15230775]])

In [23]:
np.random.randn(2,4)

array([[ 0.29256365, -0.48406136,  0.2145986 , -0.70008642],
       [-0.0598299 ,  1.99876152, -0.30068467, -0.96727507]])

In [26]:
np.random.randint(1,101,10)

array([35, 49, 78, 86, 51, 83, 74, 63, 11, 10])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([ 9, 36,  1, 43,  5, 13,  2, 15, 24, 14])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

43

In [34]:
ranarr.min()

1

In [35]:
ranarr.argmax()

3

In [36]:
ranarr.argmin()

2

In [40]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int32')

In [44]:
from numpy.random import randint 

In [45]:
randint(2,10)

9